### ISSUE TITLE
Add option to adjust a players stats

### ISSUE THREAD

**Issue by QarthO** [itHotL/PlayerStats#135]
For example
/stats deaths set qartho 0
^ this would set my deaths to 0

I understand you're using the built-in Minecraft stats and only looking up, but is there any way to change them?
idk if its possible, but def would be nice!

**Comment by Artemis-the-gr8** [comment]
You can't change the values through PlayerStats, but you can change them in the files directly!

You can find them in the world/stats folder on your server, and edit values in there with any Notepad-like program (I personally use Notepad++ with the JSON viewer plugin added, so that I can format the JSON into a big list rather than a giant one-liner).
